import type { Metadata } from 'next';
import { GeistSans } from 'geist/font/sans';

import { AppChildren } from '@/types';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: Readonly<AppChildren>) => {
  return (
    <html lang="en">
      <body className={GeistSans.className}>{children}</body>
    </html>
  );
};
export default RootLayout;
